stages:
  - validate
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: "us-east-1"
  ECR_REGISTRY: "$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com"
  ECR_REPOSITORY: "gol-chaos-backend"
  IMAGE_TAG: "latest"

cache:
  paths:
    - backend/node_modules/
    - load_injector/node_modules/
    - infrastructure/.terraform/


tf-validate:
  stage: validate
  image: 
    name: hashicorp/terraform:light
    entrypoint: [""]
  script:
    - cd infrastructure
    - terraform init -backend=false
    - terraform validate
    - terraform fmt 


build-backend-image:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - apk add --no-cache aws-cli
    - aws ecr create-repository --repository-name $ECR_REPOSITORY --region $AWS_DEFAULT_REGION || true
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  script:
    - cd backend
    - docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  only:
    - main


deploy-infrastructure:
  stage: deploy
  image: 
    name: hashicorp/terraform:light
    entrypoint: [""]
  before_script:
    # Added nodejs and npm to the alpine package installation
    - apk add --no-cache zip aws-cli nodejs npm
    # Updated to match the dashed folder name and modern npm flag
    - cd load-injector && npm install --omit=dev && cd ..
    - zip -j infrastructure/dummy_lambda.zip load-injector/*
  script:
    - cd infrastructure
    - terraform init
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
    - aws ecs update-service --cluster gol-chaos-cluster --service gol-backend-service --force-new-deployment --region $AWS_DEFAULT_REGION
  only:
    - main